---
- name: HAProxy Installation and Configuration
  hosts: haproxy
  become: true

  vars:
    haproxy_port_pg_rw: 5000
    haproxy_port_pg_ro: 5001
    haproxy_port_stats: 7000
    haproxy_bind_ip: "{{ ansible_host }}"

  tasks:
    - name: PostgreSQL node listesi başlat
      set_fact:
        postgres_nodes: []

    - name: PostgreSQL node'larını doğrudan IP'den al
      set_fact:
        postgres_nodes: "{{ postgres_nodes + [ { 'name': item, 'ip': item, 'port': 5432, 'check_port': 8008 } ] }}"
      loop: "{{ groups['postgres'] }}"

    - name: HAProxy'yi kur
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: SELinux boolean'ı aç (varsa)
      ansible.posix.seboolean:
        name: haproxy_connect_any
        state: true
        persistent: yes
      when: ansible_facts.selinux.status is defined and ansible_facts.selinux.status == "enabled"

    - name: HAProxy konfigürasyonunu oluştur
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
      notify: Restart HAProxy

    - name: HAProxy servisini başlat ve enable et
      systemd:
        name: haproxy
        state: started
        enabled: true

  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted
