---
- name: HAProxy Installation and Configuration
  hosts: haproxy
  become: true

  vars:
    haproxy_port_pg_rw: 5000
    haproxy_port_pg_ro: 5001
    haproxy_port_stats: 7000
    haproxy_bind_ip: "{{ ansible_default_ipv4.address }}"

  tasks:
    - name: Initialize PostgreSQL node list
      set_fact:
        postgres_nodes: []

    - name: List PostgreSQL nodes with IP and assign names (pg1, pg2 ...)
      set_fact:
        postgres_nodes: "{{ postgres_nodes + [ { 'name': 'pg' + (index + 1) | string, 'ip': item, 'port': 5432, 'check_port': 8008 } ] }}"
      loop: "{{ groups['postgres'] }}"
      loop_control:
        index_var: index

    - name: Install HAProxy
      dnf:
        name: haproxy
        state: present
        update_cache: yes

    - name: Create HAProxy configuration
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
      notify: Restart HAProxy

    - name: Install python3-libsemanage package
      dnf:
        name: python3-libsemanage
        state: present
      become: true

    - name: Enable SELinux boolean (haproxy_connect_any)
      ansible.posix.seboolean:
        name: haproxy_connect_any
        state: true
        persistent: yes
      become: true
      when: ansible_facts.selinux.status is defined and ansible_facts.selinux.status == "enabled"



    - name: Start and enable HAProxy service
      systemd:
        name: haproxy
        state: started
        enabled: true

  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted

