---
- name: Prepare system and install Ansible
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Install wget and tcpdump using dnf
      dnf:
        name:
          - wget
          - tcpdump
        state: present
