- name: Etcd installation (Rocky Linux 9 Minimal)
  hosts: etcd
  become: true

  vars:
    etcd_version: "v3.5.14"
    etcd_download_url: "https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    etcd_install_dir: "/usr/local/bin"

  tasks:
    - name: Install required helper packages
      yum:
        name:
          - tar
          - wget
          - curl
        state: present

    - name: Download etcd binary
      get_url:
        url: "{{ etcd_download_url }}"
        dest: /tmp/etcd.tar.gz

    - name: Extract etcd archive
      unarchive:
        src: /tmp/etcd.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Copy etcd and etcdctl binaries and make executable
      copy:
        src: "/tmp/etcd-{{ etcd_version }}-linux-amd64/{{ item }}"
        dest: "{{ etcd_install_dir }}/{{ item }}"
        mode: '0755'
        remote_src: yes
      loop:
        - etcd
        - etcdctl

    - name: Create etcd config file
      template:
        src: templates/etcd.conf.j2
        dest: /etc/default/etcd
        mode: '0644'

    - name: Create etcd systemd service file
      copy:
        dest: /etc/systemd/system/etcd.service
        content: |
          [Unit]
          Description=etcd key-value store
          Documentation=https://github.com/etcd-io/etcd
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/etcd
          Restart=always
          RestartSec=5
          LimitNOFILE=40000
          EnvironmentFile=-/etc/default/etcd

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start and enable etcd service
      systemd:
        name: etcd
        state: started
        enabled: yes

