- name: PostgreSQL & Patroni installation (Rocky Linux 9 Minimal)
  hosts: postgres
  become: true

  vars:
    pg_version: "16"
    pg_bin_path: "/usr/pgsql-16/bin"

  tasks:
    - name: Install required system packages
      yum:
        name:
          - epel-release
          - gcc
          - python3
          - python3-pip
          - python3-devel
          - libpq-devel
          - sudo
          - curl
        state: present

    - name: Download PostgreSQL PGDG .rpm file
      get_url:
        url: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
        dest: /tmp/pgdg-redhat-repo-latest.noarch.rpm
    
    - name: Download PGDG GPG key
      get_url:
        url: https://download.postgresql.org/pub/repos/yum/keys/RPM-GPG-KEY-PGDG
        dest: /tmp/RPM-GPG-KEY-PGDG
        mode: '0644'
    
    - name: Import GPG key to system
      command: rpm --import /tmp/RPM-GPG-KEY-PGDG
      args:
        creates: /etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG
 
    - name: Install PGDG .rpm file with yum
      yum:
        name: /tmp/pgdg-redhat-repo-latest.noarch.rpm
        state: present
        disable_gpg_check: true


    - name: Disable old PostgreSQL from AppStream
      shell: dnf -qy module disable postgresql

    - name: Install PostgreSQL packages (from PGDG)
      yum:
        name:
          - postgresql{{ pg_version }}
          - postgresql{{ pg_version }}-server
          - postgresql{{ pg_version }}-contrib
        state: present

    - name: Create Python virtualenv
      command: python3 -m venv /opt/patroni-venv
      args:
        creates: /opt/patroni-venv

    - name: Install Patroni and dependencies
      pip:
        virtualenv: /opt/patroni-venv
        name:
          - patroni
          - psycopg2-binary
          - python-etcd

    - name: Create Patroni config file
      template:
        src: templates/patroni.yml.j2
        dest: /etc/patroni.yml
        mode: '0644'

    - name: Copy Patroni systemd service file
      template:
        src: templates/patroni.service.j2
        dest: /etc/systemd/system/patroni.service
        mode: '0644'

    - name: Reload systemd service and start Patroni
      systemd:
        name: patroni
        daemon_reload: yes
        enabled: yes
        state: started

